# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos/faster_rcnn_box_coder.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3object_detection/protos/faster_rcnn_box_coder.proto\x12\x17object_detection.protos\"o\n\x12\x46\x61sterRcnnBoxCoder\x12\x13\n\x07y_scale\x18\x01 \x01(\x02:\x02\x31\x30\x12\x13\n\x07x_scale\x18\x02 \x01(\x02:\x02\x31\x30\x12\x17\n\x0cheight_scale\x18\x03 \x01(\x02:\x01\x35\x12\x16\n\x0bwidth_scale\x18\x04 \x01(\x02:\x01\x35')



_FASTERRCNNBOXCODER = DESCRIPTOR.message_types_by_name['FasterRcnnBoxCoder']
FasterRcnnBoxCoder = _reflection.GeneratedProtocolMessageType('FasterRcnnBoxCoder', (_message.Message,), {
  'DESCRIPTOR' : _FASTERRCNNBOXCODER,
  '__module__' : 'object_detection.protos.faster_rcnn_box_coder_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.FasterRcnnBoxCoder)
  })
_sym_db.RegisterMessage(FasterRcnnBoxCoder)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FASTERRCNNBOXCODER._serialized_start=80
  _FASTERRCNNBOXCODER._serialized_end=191
# @@protoc_insertion_point(module_scope)
