# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos/square_box_coder.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.object_detection/protos/square_box_coder.proto\x12\x17object_detection.protos\"S\n\x0eSquareBoxCoder\x12\x13\n\x07y_scale\x18\x01 \x01(\x02:\x02\x31\x30\x12\x13\n\x07x_scale\x18\x02 \x01(\x02:\x02\x31\x30\x12\x17\n\x0clength_scale\x18\x03 \x01(\x02:\x01\x35')



_SQUAREBOXCODER = DESCRIPTOR.message_types_by_name['SquareBoxCoder']
SquareBoxCoder = _reflection.GeneratedProtocolMessageType('SquareBoxCoder', (_message.Message,), {
  'DESCRIPTOR' : _SQUAREBOXCODER,
  '__module__' : 'object_detection.protos.square_box_coder_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.SquareBoxCoder)
  })
_sym_db.RegisterMessage(SquareBoxCoder)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SQUAREBOXCODER._serialized_start=75
  _SQUAREBOXCODER._serialized_end=158
# @@protoc_insertion_point(module_scope)
